upadte 2d20 roll and damage roll
Muttley/foundryvtt-fallout pull request #380
Opened 2024-05-14 10:26 UTC by bb46003

change for 2d20 roll :
 - add automatization for buing d20 dice including PC and GM, allow to buy dice for GM AP
- add button for assistance, always will roll 1d20
- reduce ammo for GM (option i settings)
- reduce 10 amo for gatling guns
change for damage roll :
- for guns fire rate can be add at begining of rolling, read weapon property and chcek if we have enough amo to shoot more bullet
- for mele/unarmed can spend max 3 AP for PC and GM
- reduce AP if avaliable for both PC and GM
- for PC buy from GM, with notification, add to GM AP automaticaly 
- add button from chat read weapon fire rate and chcek avaliable amo

2024-05-14 14:47 UTC, Muttley commented
I'll try and take a look at this after the next release.  I think it looks like it might need a bit of beautification before it can go into a release, judging by the screenshots you've shared.

2024-05-14 15:51 UTC, bb46003 commented
I was not spending much time on css just to look reasonable fine

2024-05-25 10:58 UTC, Muttley commented on i18n/pl.yaml
Please don't check in changes to the non `en.yaml` translation files, any changes will be overwritten with the next sync from Crowdin anyway.

2024-05-25 11:01 UTC, Muttley commented on i18n/en.yaml
> +FALLOUT.UI.AdditionalmeledmgOverseer: Additional damage dice for overseer AP
As mentioned in your other pull request, please try and keep keys readable. Going forward I'm trying to standardise the i18n key style to snake_case, avoiding unecessary abbreviations where possible

2024-05-25 11:07 UTC, Muttley commented on system/src/roller/Dialog2d20.mjs
There are several instances in this file where function/method names are hard to read being all lower-case with multiple words merged together.

Please make sure all function/methods names in `camelCaseFormat`.

Also, any new html being rendered should be done via relevant template files, not embedded in code please.  I'm gradually stripping out existing instances of that.

2024-05-25 11:08 UTC, Muttley commented on system/src/roller/DialogD6.mjs
There are similar problems in this file as mentioned in the comment for `Dialog2d20.mjs`

2024-05-25 11:13 UTC, Muttley commented on system/src/system/FalloutChat.mjs
> +				fallout.DialogD6.addcreateDialog({
Method names should be `camelCaseStyle`

2024-05-25 11:17 UTC, Muttley requested changes
I'm afraid you'll need to resolve any problems commented on in this code before I can safely merge it.

2024-05-25 11:17 UTC, Muttley commented on system/system.json
This change breaks the `manifest` config settings.  Please don't make changes to `system.json`

2024-06-06 09:40 UTC, bb46003 commented
I do all mentioned request, as well fixing few issue that I recognie like macros for rollind d6 or 2d20

2024-06-16 20:19 UTC, Muttley commented
Having had a play around with this, I really don't like the workflow changes this makes to the dice rolling, as it feels quite clunky and unintuitive.

I'm afraid I'm going to have to reject this one as it would be more work to resolve the issues with this implementation than it would be to write the new dice roller I'd already envisioned replacing the existing one.

2024-06-16 20:19 UTC, closed without merging